language: node_js
node_js: stable
branches:
  only:
  - main
install:
- npm install
before_script:
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注>意此处sed命令用了双引号。单引号无效！
  - sed -i "s/github_token/${GH_TOKEN}/g" _config.yml || exit 1
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
notifications: # 设置通知项
  email: true

deploy:
  on:
    branch: main                # 工作分支
  strategy: git
  provider: pages
  skip_cleanup: true            # 跳过清理
  token: $GH_TOKEN            # GitHub Token 变量
  keep_history: true            # 保持推送记录，以增量提交的方式
#  local_dir: public             # 需要推送到 gh-pages 分支的静态文件目录
#  target_branch: gh-pages       # 推送的目标文件夹 local_dir(public) -> gh-pages 分支
env:
  global:
    - GH_REF: github.com/laobameishijia/laobameishijia.github.io