name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Hexo
        run: npm install hexo-cli -g
        
      - name: Install dependencies
        run: npm install

      - name: Configure Git
      
        env:
          U_NAME: ${{ secrets.U_NAME }}
          U_EMAIL: ${{ secrets.U_EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "${{ secrets.U_NAME }}"
          git config user.email "${{ secrets.U_EMAIL }}"

      - name: Replace GitHub token in _config.yml
        run: |
          sed -i "s/github_token/${{ secrets.GH_TOKEN }}/g" _config.yml || exit 1

      - name: Clean and generate Hexo
        run: |
          hexo clean
          hexo generate

      - name: Deploy to GitHub Pages
        run: hexo deploy

  # Add additional jobs or steps as needed
